export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const DANG_KY_ACTION = 'DANG_KY_ACTION';
export const THOAT_ACTION ='THOAT_ACTION'
export const LAY_THONG_TIN_NGUOI_DUNG = 'LAY_THONG_TIN_NGUOI_DUNG'